before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Pk5Lcl9tWZzTwzuSblkHArqzHmqWKdiOZ65jcS8U5PcRDwTZSz/XFORn4f1MY8F3zlMn3W0syMSljoDWFpWpjFQ7r4X8pzYkCx1+pcJFwcrFs+s3W72ceCj8ooS3u5dOmOrnhmUrJXRe1nip6igNl5a00DM+VwYXeyiuhluGphC/xaF1Oa1xlO6iOP6U5ryt4CmLcJCapBparyS4WDo/0oT+lrkv7IGSxz2ukucokFqeQJyvOtQpVxYHGMdfxqOyZCpNM3wUSBbTgBuxXWk6aYF/0LF6Ot/s3XOVOOLi6nDEFbvHuMax0Hea6fKmtqJNd32d017yrZBoW1FjhZG7NNXRotfx/W6/K1SBGkWpetLnS06B9f+ZLOyOOQp3YJH09auuRfklSaoveojYomBTCbGhJens/6H+jTjt9d/Pt+5JEM/Was1LdtCP7buPu1pA1T66KwxUvX/aPz8aug2fDh9dxtLQX9/0QVQRZlv4HTD8Y0ZSp51YNWza87vvcTPZSjQkJFb/4XfiJH4bJFcKogiLFrANZu6TGujzQHMqIeXifVb1yyApmvN78kCPjHTPnyWFLtnKoDCDqbV2GJjj6S7OuyVTh8njYpPyjOz6EAMuB+wHUjmHUz67ARWiz9mH/UR9B6PSUgHsiPRgwDvRG98u/2C2d4xQjbLhb7vLVhA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
